name: travel_the_globe
description: "Thesis :)"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  tuple: ^1.0.3
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_database: ^4.3.0
  splashscreen: 1.2.0
  flutter_signin_button: ^1.0.0
  email_validator: ^1.0.5
  geocoding: ^1.0.5
  image: ^2.1.19
  quiver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/world.svg
    - assets/images/world.png
    - assets/images/logo.png
    - assets/images/wrld-18.png
    - assets/images/map/
    - assets/countries.json
    #https://vemaps.com/world/wrld-18
    #- images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Goldman
      fonts:
        - asset: assets/fonts/Goldman-Regular.ttf
        - asset: assets/fonts/Goldman-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
