import 'package:quiver/collection.dart';

class Countries {
  Countries() {
    _countries.addAll({
      "Afghanistan": "1",
      "Albania": "2",
      "Algeria": "3",
      "Angola": "5",
      "Argentina": "7",
      "Armenia": "8",
      "Australia": "9",
      "Austria": "A",
      "Azerbaijan": "C",
      "Bangladesh": "10",
      "Belarus": "13",
      "Belgium": "14",
      "Belize": "15",
      "Benin (Dahomey)": "16",
      "Bolivia": "17",
      "Bosnia and Herzegovina": "18",
      "Botswana": "19",
      "Brazil": "1A",
      "Bulgaria": "1D",
      "Burkina Faso (Upper Volta)": "1E",
      "Burma": "1F",
      "Burundi": "20",
      "Cambodia": "22",
      "Cameroon": "23",
      "Canada": "24",
      "Central African Republic": "26",
      "Chad": "28",
      "Chile": "29",
      "China": "2A",
      "Colombia": "2B",
      "Costa Rica": "2E",
      "Cote d’Ivoire (Ivory Coast)": "2F",
      "Croatia": "30",
      "Cuba": "31",
      "Cyprus": "32",
      "Czech republic": "34",
      "Democratic Republic of the Congo": "35",
      "Denmark": "36",
      "Djibouti": "37",
      "Dominican Republic": "39",
      "Ecuador": "3C",
      "Egypt": "3D",
      "El Salvador": "3E",
      "Equatorial Guinea": "3F",
      "Eritrea": "40",
      "Estonia": "41",
      "Ethiopia": "43",
      "Fiji": "45",
      "Finland": "46",
      "France": "47",
      "Gabon": "48",
      "Georgia": "4A",
      "Germany": "4B",
      "Ghana": "4C",
      "Greece": "4E",
      "Guatemala": "50",
      "Guinea": "51",
      "Guinea-Bissau": "52",
      "Guyana": "53",
      "Haiti": "54",
      "Honduras": "5A",
      "Hungary": "5B",
      "Iceland": "5C",
      "India": "5D",
      "Indonesia": "5E",
      "Iran": "5F",
      "Iraq": "60",
      "Ireland": "61",
      "Israel": "62",
      "Italy": "63",
      "Japan": "65",
      "Jordan": "66",
      "Kazakhstan": "67",
      "Kenya": "68",
      "Korea": "6B",
      "Kuwait": "6D",
      "Kyrgyzstan": "6E",
      "Laos": "6F",
      "Latvia": "70",
      "Lebanon": "71",
      "Liberia": "74",
      "Libya": "75",
      "Lithuania": "77",
      "Madagascar": "79",
      "Malawi": "7A",
      "Malaysia": "7B",
      "Mali": "7D",
      "Mauritania": "80",
      "Mexico": "84",
      "Moldova": "86",
      "Mongolia": "88",
      "Montenegro": "89",
      "Morocco": "8A",
      "Mozambique": "8B",
      "Namibia": "8C",
      "Nepal": "8F",
      "Netherlands, The": "90",
      "New Zealand": "91",
      "Nicaragua": "92",
      "Niger": "93",
      "Nigeria": "94",
      "North Macedonia": "97",
      "Norway": "98",
      "Oman": "9A",
      "Pakistan": "9C",
      "Panama": "9E",
      "Papua New Guinea": "A0",
      "Paraguay": "A1",
      "Peru": "A2",
      "Philippines": "A3",
      "Poland": "A5",
      "Portugal": "A6",
      "Qatar": "A7",
      "Republic of Korea (South Korea)": "A9",
      "Republic of the Congo": "AA",
      "Romania": "AB",
      "Russia": "AC",
      "Rwanda": "AD",
      "Saudi Arabia": "B4",
      "Senegal": "B6",
      "Serbia": "B7",
      "Sierra Leone": "B9",
      "Slovakia": "BB",
      "Slovenia": "BC",
      "Solomon Islands, The": "BD",
      "Somalia": "BE",
      "South Africa": "BF",
      "South Sudan": "C0",
      "Spain": "C1",
      "Sri Lanka": "C2",
      "Sudan": "C3",
      "Suriname": "C4",
      "Sweden": "C5",
      "Switzerland": "C6",
      "Syria": "C7",
      "Tajikistan": "C8",
      "Tanzania": "C9",
      "Thailand": "CB",
      "Togo": "CD",
      "Tunisia": "D0",
      "Turkey": "D1",
      "Turkmenistan": "D2",
      "Uganda": "D5",
      "Ukraine": "D6",
      "United Arab Emirates, The": "D8",
      "United Kingdom, The": "D9",
      "Uruguay": "DA",
      "Uzbekistan": "DB",
      "Vanuatu": "DC",
      "Venezuela": "DD",
      "Vietnam": "DE",
      "Yemen": "E0",
      "Zambia": "E1",
      "Zimbabwe": "E2",
      "United States": "E3",
      "Greenland": "E4",
      "Taiwan": "E5",
      "Bhutan": "E6"
    });
  }

  final BiMap<String, String> _countries = BiMap();

  String operator [](String key) {
    return _countries[key];
  }

  String getCountry(int dec) {
    return _countries.inverse[dec.toRadixString(16).toString().toUpperCase()];
  }

  Map<String, dynamic> all() {
    return _countries;
  }
}
